import { watch } from "node:fs";
import { resolve } from "node:path";
import { type Experiment, type ExperimentsConfig, validateConfig } from "@variantlab/core";
import { fileExists, readTextFile, writeTextFile } from "../utils/file.js";
import * as print from "../utils/printer.js";

export interface GenerateOptions {
  readonly config?: string | undefined;
  readonly out?: string | undefined;
  readonly watch?: boolean | undefined;
  readonly verbose?: boolean | undefined;
}

export async function generate(options: GenerateOptions = {}): Promise<number> {
  const configPath = resolve(options.config ?? "experiments.json");
  const outPath = resolve(options.out ?? "src/variantlab.generated.ts");

  const code = await runGenerate(configPath, outPath, options.verbose ?? false);
  if (code !== 0) return code;

  if (options.watch) {
    print.info(`Watching ${configPath} for changes...`);
    let debounce: ReturnType<typeof setTimeout> | null = null;
    watch(configPath, () => {
      if (debounce) clearTimeout(debounce);
      debounce = setTimeout(async () => {
        print.info("Config changed, regenerating...");
        await runGenerate(configPath, outPath, options.verbose ?? false);
      }, 100);
    });
    // Keep process alive in watch mode
    await new Promise(() => {});
  }

  return 0;
}

async function runGenerate(
  configPath: string,
  outPath: string,
  isVerbose: boolean,
): Promise<number> {
  if (!(await fileExists(configPath))) {
    print.error(`Config not found: ${configPath}`);
    return 1;
  }

  let raw: string;
  try {
    raw = await readTextFile(configPath);
  } catch (err) {
    print.error(`Failed to read config: ${(err as Error).message}`);
    return 3;
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch (err) {
    print.error(`Invalid JSON: ${(err as Error).message}`);
    return 2;
  }

  let config: ExperimentsConfig;
  try {
    config = validateConfig(parsed);
  } catch (err) {
    print.error(`Validation failed: ${(err as Error).message}`);
    return 2;
  }

  print.verbose(`Loaded ${config.experiments.length} experiment(s)`, isVerbose);

  const output = emitTypeScript(config);

  try {
    await writeTextFile(outPath, output);
  } catch (err) {
    print.error(`Failed to write output: ${(err as Error).message}`);
    return 3;
  }

  print.success(`Generated ${outPath}`);
  return 0;
}

function emitTypeScript(config: ExperimentsConfig): string {
  const lines: string[] = [
    "// AUTO-GENERATED by @variantlab/cli",
    `// Generated at ${new Date().toISOString()}`,
    "// DO NOT EDIT BY HAND",
    "// Regenerate with: variantlab generate",
    "",
    "export interface VariantLabExperiments {",
  ];

  for (const exp of config.experiments) {
    if (exp.name) {
      lines.push(`  /** ${escapeComment(exp.name)} */`);
    }
    lines.push(`  "${exp.id}": {`);
    lines.push(`    type: "${exp.type ?? "render"}";`);
    lines.push(`    variants: ${variantUnion(exp)};`);
    lines.push(`    default: "${exp.default}";`);

    if (exp.type === "value") {
      lines.push(`    value: ${valueUnion(exp)};`);
    }

    lines.push("  };");
  }

  lines.push("}");
  lines.push("");
  lines.push('declare module "@variantlab/core" {');
  lines.push("  interface VariantLabRegistry extends VariantLabExperiments {}");
  lines.push("}");
  lines.push("");
  lines.push("export type ExperimentId = keyof VariantLabExperiments;");
  lines.push("");
  lines.push("export type VariantId<T extends ExperimentId> =");
  lines.push('  VariantLabExperiments[T]["variants"];');
  lines.push("");
  lines.push("export type VariantValueType<T extends ExperimentId> =");
  lines.push("  VariantLabExperiments[T] extends { value: infer V } ? V : never;");
  lines.push("");

  return lines.join("\n");
}

function variantUnion(exp: Experiment): string {
  return exp.variants.map((v) => `"${escapeStr(v.id)}"`).join(" | ");
}

function valueUnion(exp: Experiment): string {
  const values = exp.variants.map((v) => v.value).filter((v) => v !== undefined);

  if (values.length === 0) return "never";

  return values
    .map((v) => {
      if (typeof v === "string") return `"${escapeStr(v)}"`;
      if (typeof v === "number" || typeof v === "boolean") return String(v);
      return "unknown";
    })
    .join(" | ");
}

function escapeStr(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function escapeComment(s: string): string {
  return s.replace(/\*\//g, "* /");
}
