/**
 * Machine-readable issue codes for `ConfigValidationError`.
 *
 * This is a **type-only** module — no runtime export. Consumers
 * that need to switch on the code do so against the string
 * literals (the compiler narrows them).
 *
 * The list is append-only in minor versions.
 */
export type IssueCode =
  | "invalid-json"
  | "not-an-object"
  | "config-too-large"
  | "reserved-key"
  | "version/missing"
  | "version/invalid"
  | "enabled/invalid"
  | "signature/invalid"
  | "experiments/missing"
  | "experiments/not-an-array"
  | "experiments/too-many"
  | "experiment/not-an-object"
  | "experiment/missing-required"
  | "experiment/id/invalid"
  | "experiment/id/duplicate"
  | "experiment/name/invalid"
  | "experiment/description/invalid"
  | "experiment/type/invalid"
  | "experiment/status/invalid"
  | "experiment/variants/missing"
  | "experiment/variants/too-few"
  | "experiment/variants/too-many"
  | "variant/not-an-object"
  | "variant/id/invalid"
  | "variant/id/duplicate"
  | "variant/label/invalid"
  | "variant/description/invalid"
  | "experiment/default/missing"
  | "experiment/default/unknown-variant"
  | "experiment/assignment/invalid"
  | "split/missing"
  | "split/not-an-object"
  | "split/unknown-variant"
  | "split/value-invalid"
  | "split/sum-invalid"
  | "experiment/routes/invalid"
  | "route/glob/invalid"
  | "targeting/not-an-object"
  | "targeting/depth-exceeded"
  | "targeting/platform/invalid"
  | "targeting/appversion/invalid"
  | "targeting/locale/invalid"
  | "targeting/screensize/invalid"
  | "targeting/routes/invalid"
  | "targeting/userid/invalid"
  | "targeting/attributes/invalid"
  | "experiment/startdate/invalid"
  | "experiment/enddate/invalid"
  | "experiment/date-range/invalid"
  | "experiment/mutex/invalid"
  | "experiment/owner/invalid"
  | "experiment/overridable/invalid"
  | "rollback/not-an-object"
  | "rollback/threshold/invalid"
  | "rollback/window/invalid"
  | "rollback/persistent/invalid";
